### ISSUE TITLE
Svelte3SSR/Svelte3SSRResult classes missing

### ISSUE THREAD

**Issue by 1fexd** [tncrazvan/java-springboot-svelte3-ssr-template#3]
Hello,

I just took a look [Svelte3SSRService.java](https://github.com/tncrazvan/java-springboot-svelte3-ssr-template/blob/master/src/main/java/com/github/tncrazvan/svelte3ssr/template/services/Svelte3SSRService.java) which imports `com.github.tncrazvan.svelte3ssr.Svelte3SSR` and `com.github.tncrazvan.svelte3ssr.Svelte3SSRResult` which seem to be missing from the sourcecode (maybe you forgot to add them to the repo/forgot to commit them).

**Comment by razshare** [comment]
Yes, they do miss, that's because they're 2 different projects.
The "svelte3ssr" project is a dependency of the "svelte3ssr-template" project.
Take a look at this: https://github.com/tncrazvan/java-springboot-svelte3-ssr-template/blob/2ab172ca2fc8b431273588f42a04cf78a75388e5/pom.xml#L19

and this:
https://github.com/tncrazvan/java-springboot-svelte3-ssr-template/blob/2ab172ca2fc8b431273588f42a04cf78a75388e5/pom.xml#L51

You will need to make your maven download them.
`mvn install` usualy works fine, but if you're on netbeans for example, simply "build" your project before running it and it should download all dependencies.

Or, again if you're using netbeans, force the download:
![image](https://user-images.githubusercontent.com/6891346/97816008-76de1180-1c92-11eb-8924-2329709f33d1.png)

**Comment by razshare** [comment]
The classes you mentioned can be found here: https://github.com/tncrazvan/java-svelte3-ssr
You can use them to make your own spring service or implement them in some other non spring project.

Let me know if you got it working

**Comment by 1fexd** [comment]
Oh I see - thank you, I'll take a look at it!
